//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slide_generator.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("slide_generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;script&gt;
        /////MUDAR AQUI O TEMPO ENTRE TROCA DE IMAGENS
        ///var TEMPO_ENTRE_SLIDES = @NRO_SEGUNDOS * 1000;
        ///&lt;/script&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Simple slide!&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;style&gt;
        ///* {box-sizing:border-box}
        ///.slideshow-container 
        ///{
        ///	max-width: 90%;
        ///	position: relative;
        ///	margin: auto;
        ///}
        ///img
        ///{
        ///	object-fit:contain;
        ///	width:90%;
        ///	height:90%;
        ///}
        ///.fade 
        ///{
        ///	-webkit-animation-name: fade;
        ///	-webkit-animation-duration: 3.5s;
        ///	animation-name: fade;
        ///	animation-duration: 3.5s;
        ///	display:flex; place-content:  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string dummy {
            get {
                return ResourceManager.GetString("dummy", resourceCulture);
            }
        }
    }
}
